service: photodrop-photos-trigger

frameworkVersion: "3"
useDotenv: true
provider:
  name: aws
  environment: ${file(env.json)}
  runtime: nodejs14.x
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - "arn:aws:s3:::*"
functions:
  photoTrigger:
    handler: src/lambdas/photos.handler
    timeout: 60
    events:
      - s3:
          bucket: photodrop-photos-default
          event: s3:ObjectCreated:*
  selfiesTrigger:
    handler: src/lambdas/selfies.handler
    timeout: 60
    events:
      - s3:
          bucket: photodrop-selfies-default
          event: s3:ObjectCreated:*

plugins:
  - serverless-plugin-typescript
